require('dotenv').config()
let {userDB,vendorDB,proposalDB} = require('./connector')
const express =require('express')
const app=express()
app.listen(process.env.PORT,()=>{console.log('listening on port'+process.env.PORT)})
app.get('/',(req,res)=>{res.send('welcome')})